[build]
  publish = "dist"  # Adjust this to match the directory where your build files are output
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy?url=:splat"
  status = 200
  force = true